name: "vaultlocker"

on:
  - pull_request
  - push

jobs:
  run_tests_vault:
    strategy:
      max-parallel: 3
      matrix:
        requirements:
          - noble
          - resolute
          - latest
        vault_versions:
          - '1.8'
          - '1.18'
          - '2.0'
        include:
          - requirements: noble
            python_version: '3.12'
          - requirements: resolute
            python_version: '3.14'
          - requirements: latest
            python_version: '3.14'
    runs-on: ubuntu-latest
    services:
      vault:
        image: hashicorp/vault:${{ matrix.vault_versions }}
        env:
          VAULT_DEV_ROOT_TOKEN_ID: "testing"
        ports:
          - 8200:8200
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python_version }}
      - name: "install requirements"
        run: |
          if [ "${{ matrix.requirements }}" = "latest" ]; then
            pip install -r requirements.txt
          else
            pip install -r requirements-${{ matrix.requirements }}.txt
          fi
          pip install -r test-requirements.txt
          pip install .
      - name: "flake8 run"
        run: |
          flake8
      - name: "run unit tests"
        run: |
          stestr run "^vaultlocker.tests.unit.*"
      - name: "run functional tests"
        env:
          PIFPAF_VAULT_ADDR: "http://127.0.0.1:8200"
          PIFPAF_ROOT_TOKEN: "testing"
        run: |
          stestr run "^vaultlocker.tests.functional.*"
