name: "vaultlocker"

on:
  - pull_request
  - push

jobs:
  run_tests_vault:
    strategy:
      max-parallel: 3
      matrix:
        include:
          - python_version: '3.8'
            os: "ubuntu-20.04"
            openstack_constraints: 'https://opendev.org/openstack/requirements/raw/tag/ussuri-eol/upper-constraints.txt'
          - python_version: '3.10'
            os: "ubuntu-22.04"
            openstack_constraints: 'https://opendev.org/openstack/requirements/raw/tag/yoga-eom/upper-constraints.txt'
          - python_version: '3.12'
            os: "ubuntu-24.04"
            openstack_constraints: 'https://opendev.org/openstack/requirements/raw/branch/stable/2024.1/upper-constraints.txt'
          - python_version: '3.14'
            os: "ubuntu-26.04"
            openstack_constraints: 'https://opendev.org/openstack/requirements/raw/branch/stable/2026.1/upper-constraints.txt'
        python_version:
          - '3.8'
          - '3.10'
          - '3.12'
          - '3.14'
        vault_version:
          # k8s based vault
          - '2.0'
          - '1.19'
          - '1.18'
          - '1.17'
          - '1.16'
          - '1.15'
          # charmed openstack's vault
          - '1.8'
    runs-on: ${{ matrix.os }}
    services:
      vault:
        image: hashicorp/vault:${{ matrix.vault_version }}
        env:
          VAULT_DEV_ROOT_TOKEN_ID: "testing"
        ports:
          - 8200:8200
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_versions }}
      - name: "install requirements"
        run: |
          pip install -r requirements.txt -c ${{ matrix.openstack_constraints }}
          pip install -r test-requirements.txt -c ${{ matrix.openstack_constraints }}
      - name: "flake8 run"
        run: |
          flake8
      - name: "run unit tests"
        run: |
          stestr run "^vaultlocker.tests.unit.*"
      - name: "run functional tests"
        run: |
          stestr run "^vaultlocker.tests.functional.*"
